# Fill Simulator Latency Configuration

[latency]
# Strategy market data latency in nanoseconds
strategy_md_latency_ns = 1000  # 1µs

# Exchange latency (one-way) in nanoseconds
exchange_latency_ns = 10000  # 10µs

[simulation]
# Whether to use queue simulation (true) or tops/fills (false)
use_queue_simulation = true

[strategy]
# Theo strategy parameters
# Minimum edge required to place a new order (as percent)
place_edge_percent = 0.01
# Minimum edge required to keep an existing order (as percent)
cancel_edge_percent = 0.005